// Package externalref provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 DO NOT EDIT.
package externalref

import (
	externalRef0 "github.com/deepmap/oapi-codegen/v2/internal/test/externalref/packageA"
	externalRef1 "github.com/deepmap/oapi-codegen/v2/internal/test/externalref/packageB"
)

// Container defines model for Container.
type Container struct {
	ObjectA *externalRef0.ObjectA `json:"object_a,omitempty"`
	ObjectB *externalRef1.ObjectB `json:"object_b,omitempty"`
}
